--CONSULTA DE LA TABLA COMPLETA DE PRODUCTOS
-- SELECT * FROM "esquema"."PRODUCTOS"

--CONSULTA CANTIDAD DE FILAS DE LA TABLA HAYA O NO NULL
-- SELECT COUNT(*) FROM "esquema"."PRODUCTOS"

--CONSULTA LA CANTIDAD DE FILAS QUE NO TENGA NULL ESA COLUMNA
-- SELECT COUNT("DESCRIPCION") FROM "esquema"."PRODUCTOS"
